Stat svc
lliauh/java-explore-with-me pull request #1
Opened 2024-07-01 22:00 UTC by lliauh

2024-07-03 13:45 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-07-03 13:45 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/validation/StatsRequestValidation.java
> +public class StatsRequestValidation {
мне кажется валидацию лучше сделать через аннотации.
@RequestParam String start, @RequestParam String end -- можно прям здесь их добавить
@RequestParam @SomeAnnotation String start

2024-07-03 13:45 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/model/Hit.java
> +@RequiredArgsConstructor
это вам не надо

2024-07-03 13:45 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/service/StatsServiceImpl.java
> +    private LocalDateTime decodeDateFromParam(String date) {
смотрите коммент в StatsController -- этот метод не нужен

2024-07-03 13:45 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/controller/StatsController.java
> +    public StatsDto[] getStats(@RequestParam String start, @RequestParam String end,
Зачем String, можно сразу LocalDate, переименуйте в startDate, endDate, будет примерно так:
@RequestParam@DateTimeFormat(iso = DateTimeFormat.ISO.DATE) LocalDate startDate

2024-07-03 13:45 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/controller/StatsController.java
> +    public StatsDto[] getStats(@RequestParam String start, @RequestParam String end,
StatsDto[] -- почему не коллекция??

2024-07-03 13:45 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/service/StatsServiceImpl.java
> +            StatsDto[] statsArray = new StatsDto[allStats.size()];
зачем массив??

2024-07-03 16:10 UTC, lliauh commented on stats-service/stats-server/src/main/java/ru/practicum/stats/model/Hit.java
> +@RequiredArgsConstructor
вот тут единственное недопонял, как тогда идет провязка с табличкой? я был уверен, что через аннотации @Entity
@Table(name = "hits")
я задаю связь с моделью, что вот та сущность, которая в табличке будет храниться

или потому что у меня одна табличка и 1 моделька, то поэтому прописывать не надо?

2024-07-03 16:40 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/model/Hit.java
> +@RequiredArgsConstructor
Вам не нужна аннотация @RequiredArgsConstructor

2024-07-04 17:07 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
только перед мержем поправьте комменты

2024-07-04 17:07 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/controller/StatsController.java
> +    public List<StatsDto> getStats(@RequestParam @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss") LocalDateTime start,
startDate и endDate

2024-07-04 17:07 UTC, ErkinKasymaliev commented on stats-service/stats-server/src/main/java/ru/practicum/stats/service/StatsServiceImpl.java
> +    public List<StatsDto> getStats(LocalDateTime start, LocalDateTime end, String[] uris, Boolean unique) {
startDate, endDate

2024-07-04 19:12 UTC, merged