feat: add event reviews and ratings feature
lliauh/java-explore-with-me pull request #3
Opened 2024-07-18 00:41 UTC by lliauh

2024-07-18 12:18 UTC, ErkinKasymaliev requested changes
привет, оставил комменты

2024-07-18 12:18 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/ewm/events/service/EventServiceImpl.java
> +                ratingMap.put(eventId, null);
а это надо - null в map ложить?

2024-07-18 12:18 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/ewm/reviews/dto/ReviewMapper.java
> +@NoArgsConstructor(access = AccessLevel.PRIVATE)
эта аннотация лишняя

2024-07-18 12:18 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/ewm/reviews/dto/ReviewToEventDto.java
> +    public UserShortDto reviewer;
private

2024-07-18 12:18 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/ewm/reviews/dto/ReviewDto.java
> +    public UserShortDto reviewer;
private

2024-07-18 12:18 UTC, ErkinKasymaliev commented on ewm-service/src/main/java/ru/practicum/ewm/reviews/service/ReviewServiceImpl.java
> +        if (!event.getState().equals(EventState.PUBLISHED) || event.getEventDate().isAfter(LocalDateTime.now())) {
enum-ы можно через == сравнивать

2024-07-18 12:27 UTC, lliauh commented on ewm-service/src/main/java/ru/practicum/ewm/events/service/EventServiceImpl.java
> +                ratingMap.put(eventId, null);
да, погорячился в ночи, спасибо)

2024-07-19 13:19 UTC, ErkinKasymaliev approved these changes
привет, работа принята!
Поздравлю с успешным окончанием курса!

2024-07-19 13:21 UTC, merged